# Generated by Django 5.1.7 on 2025-04-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pecas',
            new_name='Peca',
        ),
    ]
