# Generated by Django 5.1.7 on 2025-05-28 11:04

import oficina.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_rename_pecas_peca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15, validators=[oficina.models.validar_telefone])),
                ('email', models.EmailField(max_length=254)),
                ('veiculo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descreva o modelo do veículo')),
                ('placa_do_veiculo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do veículo')),
                ('servico_desejado', models.CharField(choices=[('troca_oleo', 'Troca de Óleo'), ('sistema_eletrico', 'Sistema Elétrico'), ('mecanica_geral', 'Mecânica Geral'), ('injecao_eletronica', 'Injeção Eletrônica'), ('alinhamento_balanceamento', 'Alinhamento e Balanceamento'), ('ar_condicionado', 'Ar Condicionado'), ('outro', 'Outro')], max_length=30, verbose_name='Serviço desejado')),
                ('data_preferencial', models.DateField(verbose_name='Data preferencial')),
                ('horario_preferencial', models.TimeField(verbose_name='Horário preferencial')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Descreva o problema ou informe detalhes adicionais')),
            ],
        ),
    ]
