# Generated by Django 5.1.7 on 2025-05-15 13:47

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_funcionario', models.CharField(max_length=50, verbose_name='Escreva o nome completo do Colaborador.')),
                ('data_de_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço do Colaborador')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[core.models.validar_cpf_model], verbose_name='CPF do Colaborador')),
                ('matricula', models.CharField(max_length=50)),
                ('data_de_contratacao', models.DateField()),
                ('numero_telefone_colaborador', models.CharField(max_length=15, validators=[core.models.validar_telefone], verbose_name='Nº telefone celular')),
                ('email_colaborador', models.EmailField(max_length=100, verbose_name='Insira o e-mail do colaborador')),
                ('departamento', models.CharField(blank=True, choices=[('RH', 'RECURSOS HUMANOS'), ('VE', 'VENDAS'), ('MEC', 'MECANICOS'), ('ADM', 'ADMINISTRATIVO'), ('TI', 'TECNOLOGIA DA INFORMAÇÃO')], max_length=4)),
                ('cargo_do_colaborador', models.CharField(max_length=40, verbose_name='Cargo do Colaborador')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('AFASTADO', 'Afastado'), ('DEMITIDO', 'Demitido'), ('FERIAS', 'Férias')], default='ATIVO', max_length=10)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='colaboradores/', verbose_name='Foto de Perfil')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário do Colaborador')),
                ('horario_trabalho', models.CharField(max_length=50, verbose_name='Horário de Trabalho')),
                ('avaliacao_desempenho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Avaliação de Desempenho')),
            ],
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], max_length=20)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias_utilizados', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='FolhaDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_ano', models.DateField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pendente', max_length=10)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_treinamento', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('certificado', models.BooleanField(default=False)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colaborador')),
            ],
        ),
    ]
